services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Twig\ValidatorExtension:
        public: false
        tags:
        - { name: 'twig.extension' }

    App\Twig\WeekdayExtension:
        public: false
        tags:
        - { name: 'twig.extension' }
